name: Deploy docker image to private registry (if commit message contains ~deploy~)

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Create docker image and push to private registry
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '~deploy~')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          context: .
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/${{ github.event.repository.name }}:latest
        env:
          DOCKER_BUILDKIT: 1
